#
# Configuration file for the AdminLTE bundle
#
# For more information about the bundle settings visit:
# https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/configurations.md
#
layout_core:
  options:
    # default image for missing user avatar images
    default_avatar: bundles/layoutcore/images/default_avatar.png
    # the color skin
    skin: skin-blue
    
  routes:
    layoutcore_welcome: index
    layoutcore_login: index
    layoutcore_login_check: index
    layoutcore_message: index
    layoutcore_messages: index
    layoutcore_notification: index
    layoutcore_notifications: index
    layoutcore_task: index
    layoutcore_tasks: index
    layoutcore_profile: index
