#
# Configuration file for the AdminLTE bundle
#
# For more information about the bundle settings visit:
# https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/configurations.md
#
layout_core:
  options:
    # default image for missing user avatar images
    default_avatar: bundles/layoutcore/images/default_avatar.png
    # the color skin
    skin: skin-blue
 
  routes:
    layoutcore_login: welcome
    layoutcore_login_check: welcome
    layoutcore_profile: welcome
    layoutcore_welcome: welcome
 
